---
- name: Configurar user.name
  become_user: "{{ item.name }}"
  ansible.builtin.git_config:
    name: user.name
    value: "{{ item.git_name }}"
    scope: global
  loop: "{{ dev_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configurar user.email
  become_user: "{{ item.name }}"
  ansible.builtin.git_config:
    name: user.email
    value: "{{ item.git_email }}"
    scope: global
  loop: "{{ dev_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configurar opciones globales de Git
  become_user: "{{ item.0.name }}"
  ansible.builtin.git_config:
    name: "{{ item.1.key }}"
    value: "{{ item.1.value }}"
    scope: global
  loop: "{{ dev_users | product(git_global_config | dict2items) | list }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1.key }}"
